### ISSUE TITLE
looking to share a ride? Ask here!

### ISSUE THREAD

**Issue by gilligan** [BusConf/community#3]
Are you looking for someone to share a taxi with or just generally would rather like to travel together? Just announce your travel route here to find travel mates :)

**Comment by wosc** [comment]
I'll arrive at Aschaffenburg by train on Thursday 16:42 and would be happy to share a taxi. :)

**Comment by axelhodler** [comment]
@wosc would gladly share a taxi too. time is perfect.

**Comment by sengaya** [comment]
I'll arrive at that time as well, would gladly share a taxi, too.

**Comment by jlink** [comment]
@wosc I'll arrive 16:38 (if train is on time). Give me a call or a message: +49 162 6282764

**Comment by wosc** [comment]
Alright, that's 4 taxi people at around 17:00 already. :)

**Comment by wosc** [comment]
@axelhodler @sengaya @jlink So... let's all meet at the [randomly chosen](https://www.xkcd.com/221/) track number 4 (I don't know the station well enough to suggest another easily identifiable meeting spot) and head for the taxis at about 17:00.

**Comment by jlink** [comment]
@wosc @sengaya @axelhodler Since a track is actually rather long I suggest the place in front of the pharmacy outside the station building which is very close to the taxi stand.
