### ISSUE TITLE
Looking to share a ride?

### ISSUE THREAD

**Issue by gilligan** [BusConf/community#4]
Are you looking for a ride or want to offer a seat in your car? Announce it here!

**Comment by jlink** [comment]
Is someone going through Heidelberg (or close by) on their way to Rückersbach?

**Comment by rodrijuarez** [comment]
Does anyone go from Berlin or pass through it?

**Comment by gradorsys** [comment]
Hi, i am coming from Nürnberg by car and have 1 slot free.
I plan to leave Nürnberg ~2pm on Thursday.

**Comment by 3v0k4** [comment]
I'm gonna be spending the night in Frankfurt tomorrow. Let me know if you are up to meet and / or share a taxi (or train) to the conf ;)

**Comment by stefanholzmueller** [comment]
I'll arrive at Aschaffenburg on Thursday 18:15 ... anyone wants to share a taxi around that time?

**Comment by paulcadman** [comment]
I'm arriving at Frankfurt airport at 16:30 Thursday, assuming I get the 17:30 train from the airport I'll get to Aschaffenburg at 18:20, so I could share with you @stefanholzmueller .

**Comment by jlink** [comment]
I'll probably arrive 16:15 Aschaffenburg Hbf. Would like to share a cab.

**Comment by gilligan** [comment]
I will be at Aschaffenburg at 16:50 - if anyone wants to share a cab, let me know!

(I’m coming by train via Baden Baden/Frankfurt)

**Comment by rodrijuarez** [comment]
I’ll be at Frankfurt main station (hbf) around 17:45, is someone going from there to the hotel or to the other train station (Aschaffenburg Hauptbahnhof)?

**Comment by rodrijuarez** [comment]
@paulcadman @stefanholzmueller I'll probably also arrive to Aschaffenburg around that time, so if anyone of you wants to share taxi I'm down i

**Comment by mafulafunk** [comment]
@all I just set up a doodle for expected time of arrival at Aschaffenburg Main Station. Maybe this helps for ride shares.

https://doodle.com/poll/rrybrdcx63wpmn5n

I plan, to be there by ~~18:50~~ or 19:13

**Comment by stefanholzmueller** [comment]
Okay, 18:30 seems to be a good time to fill a taxi. I'll bring a sign that reads "BUS CONF" and loiter in the middle of the station building.

**Comment by axelhodler** [comment]
~~arriving at aschaffenburg 16:13 by train~~

~~@jlink lets meet at the taxi area outside of the station?~~

changes to 16:50 due to some delays

**Comment by jlink** [comment]
@axelhodler We seem to be in the same train and could even meet there (01726282764). Otherwise at the taxi stand.

**Comment by andreassimon** [comment]
My train is scheduled to arrive at Aschaffenburg at 15:22. Anybody else there so early? If not, I'll wait at the station for a few of you.

**Comment by ghost** [comment]
I'll arrive at 18:22, by the same train as a few of you I guess, so hopefully I'll join a group sharing a cab at that time.

**Comment by rodrijuarez** [comment]
Train delayed, I'll be at Aschaffenburg around 9...

**Comment by mafulafunk** [comment]
Still 19:13. Anyone else?
